const translations = {
  en: {
    "nav.portafolio": "PORTFOLIO",
    "nav.servicios": "SERVICES",
    "nav.branding": "BRANDING",
    "nav.redes": "SOCIAL MEDIA & ADS",
    "nav.web": "WEB DESIGN",
    "nav.suscripcion": "SUBSCRIPTION",
    "nav.nosotros": "ABOUT US",
    "nav.quienes": "WHO WE ARE",
    "nav.metodologia": "METHODOLOGY",
    "nav.blog": "BLOG",
    "button.portafolio": "Portfolio",
    "hero.title.1": "Be the",
    "hero.title.2": "chosen",
    "hero.title.3": "brand by your customers.",
    "hero.subtitle": "We are a strategic branding agency specialized in the creation and transformation of brands. We help you grow and stand out.",
    "hero.stats.projects": "Completed Projects",
    "hero.stats.clients": "Clients",
    "hero.stats.years": "Years of Experience",
    "hero.stats.countries": "Countries",
    "portfolio.title": "Our Portfolio",
    "portfolio.description": "From your new logo to the visual and verbal manual, we will equip you with the necessary tools to (re)launch yourself successfully as a fully aligned brand from day one.",
    "portfolio.button": "Free Consultation",
    our_services: "Our Services",
    branding: "Branding",
    social_media: "Strategic Social Media",
    btl_activations: "BTL Activations",
    web_development: "Web Development",
    audiovisual_production: "Audiovisual Production",
    advisory: "Advisory and Analysis",
    see_more: "See more",
    "packages.title": "Our Packages",
    "packages.description": "Our packages are the perfect foundation for any brand, regardless of size.",
    "packages.tab.branding": "BRANDING",
    "packages.tab.social": "SOCIAL MEDIA + ADS",
    "packages.tab.web": "WEB DEVELOPMENT",
    "packages.branding.basic.title": "Essential Branding",
    "packages.branding.basic.time": "2 - 3 WEEKS",
    "packages.branding.basic.items.logo": "Logo design (main version + secondary versions)",
    "packages.branding.basic.items.palette": "Color palette and typography",
    "packages.branding.basic.items.manual": "Brand manual (logo usage, colors, visual style)",
    "packages.branding.basic.items.mockups": "Mockups to visualize how your brand will look on various media (cards, stationery, social media)",
    "packages.branding.basic.items.social": "Social media designs (profile, cover, and intro posts)",
    "packages.branding.basic.items.card": "Digital business card",
    "packages.branding.basic.items.files": "Editable files ready for print and digital use",
    "packages.branding.basic.price": "FROM S/700 + TAX",
  
    "paquetes.redes.basico.titulo": "Basic Package",
    "paquetes.redes.basico.item1": "5 Reels per month",
    "paquetes.redes.basico.item2": "5 Posts per month",
    "paquetes.redes.basico.item3": "8 Stories (8 content adaptations)",
    "paquetes.redes.basico.item4": "1 recording session",
    "paquetes.redes.basico.item5": "Monthly photos",
    "paquetes.redes.basico.item6": "4 ads (ADS)",
    "paquetes.redes.basico.item7": "Advisory Level 1",
    "paquetes.redes.basico.item8": "Influencer contact",
    "paquetes.redes.basico.item9": "Strategic meeting included",
    "paquetes.redes.basico.precio": "S/1400",
    "paquetes.redes.premium.titulo": "Premium Package",
    "paquetes.redes.premium.item1": "6 Reels per month",
    "paquetes.redes.premium.item2": "6 Posts per month",
    "paquetes.redes.premium.item3": "Printed flyers (4 types): stationery, signs, etc.",
    "paquetes.redes.premium.item4": "12 Stories (12 content adaptations)",
    "paquetes.redes.premium.item5": "2 recording sessions",
    "paquetes.redes.premium.item6": "Monthly photos",
    "paquetes.redes.premium.item7": "6 ads (ADS)",
    "paquetes.redes.premium.item8": "2 monthly campaigns",
    "paquetes.redes.premium.item9": "Performance report (META)",
    "paquetes.redes.premium.item10": "Advisory Level 2",
    "paquetes.redes.premium.item11": "Influencer contact",
    "paquetes.redes.premium.item12": "Strategic meeting included",
    "paquetes.redes.premium.precio": "S/1800",
    "paquetes.redes.elite.titulo": "Elite Package",
    "paquetes.redes.elite.item1": "8 Reels per month",
    "paquetes.redes.elite.item2": "10 Posts per month",
    "paquetes.redes.elite.item3": "Printed flyers (6 types): stationery, merchandising, signs, etc.",
    "paquetes.redes.elite.item4": "18 Stories (18 content adaptations)",
    "paquetes.redes.elite.item5": "2 recording sessions",
    "paquetes.redes.elite.item6": "Monthly photos",
    "paquetes.redes.elite.item7": "10 ads (ADS)",
    "paquetes.redes.elite.item8": "3 monthly campaigns",
    "paquetes.redes.elite.item9": "Performance report (META + TikTok)",
    "paquetes.redes.elite.item10": "Advisory Level 3",
    "paquetes.redes.elite.item11": "Influencer contact",
    "paquetes.redes.elite.item12": "Strategic meeting included",
    "paquetes.redes.elite.precio": "S/2400",
    "paquetes.redes.tiempo": "PER MONTH",

    

    "paquete.landing.title": "Landing Page Development",
    "paquete.landing.1": "Unique design that reflects your brand style",
    "paquete.landing.2": "Fast website compatible with mobile, PC, and tablet",
    "paquete.landing.3": "SEO so Google can find you",
    "paquete.landing.4": "Direct links to WhatsApp and social media",
    "paquete.landing.5": "Photo and video gallery for your brand",
    "paquete.landing.6": "Form for bookings and inquiries",
    "paquete.landing.precio": "FROM S/800 + TAX",

    "paquete.ecommerce.title": "E-commerce",
    "paquete.ecommerce.1": "Responsive and personalized design",
    "paquete.ecommerce.2": "Integration with payment gateways",
    "paquete.ecommerce.3": "Shopping cart and optimized checkout",
    "paquete.ecommerce.4": "Full product and order management",
    "paquete.ecommerce.5": "Automated notifications",
    "paquete.ecommerce.6": "Friendly URLs, fast load and proper tagging",
    "paquete.ecommerce.precio": "FROM S/1800 + TAX",

    "paquete.app.title": "Web / Mobile / Desktop Apps",
    "paquete.app.1": "Custom web and mobile apps",
    "paquete.app.2": "Secure login and user control",
    "paquete.app.3": "Scalable and secure database",
    "paquete.app.4": "Custom admin panel",
    "paquete.app.5": "Push or real-time notifications",
    "paquete.app.6": "Integration with APIs and external services",
    "paquete.app.precio": "FROM S/3500 + TAX",

    "asesoria.boton": "Free Consultation",

    "clients.trust": "They trust us",
    "question.title": "Does your business feel like this?",
    "question.description": "If you identify with this, it's time to rethink your brand strategy. At <strong>PosteaLab</strong>, we help you build a clear, coherent, and powerful identity.",
    "question.cta": "Free consultation",
    "question.list.item1": "Your competitors have a clear value proposition, while you feel scattered and lack a defined focus.",
    "question.list.item2": "Your message is inconsistent: every team member describes the business differently.",
    "question.list.item3": "You focus on selling products, but not on solving your customers' real problems.",
    "question.list.item4": "You're about to launch your brand or product and need to connect with your audience from day one.",
    "question.list.item5": "You feel your business needs a clear direction and a well-defined purpose.",
    "question.list.item6": "You're not satisfied with your brand's current perception and know it can go much further.",
    "proceso.title": "Our Process",
    "proceso.subtitle": "Dynamic and focused, it's not just our team, it's our process.",
    "proceso.step1.title": "ON BOARDING",
    "proceso.step1.phase": "VISION",
    "proceso.step1.description": "We meet with you and your team to analyze the needs of your business growth in order to advise and provide our analysis and recommendations.",
    "proceso.step2.title": "SCHEDULING",
    "proceso.step2.phase": "IDEALIZATION",
    "proceso.step2.description": "We idealize the perfect feed for you and brainstorm ideas with your team to enhance your brand through the content we will create.",
    "proceso.step3.title": "PRE-PRO-POST",
    "proceso.step3.phase": "PRODUCTION",
    "proceso.step3.description": "One of our leaders will take your project and, along with the entire Postea Lab team, produce all the content for the month to give you a unique, value-filled feed.",
    "proceso.step4.title": "DIFFUSION",
    "proceso.step4.phase": "PUBLICATION AND MEDIA",
    "proceso.step4.description": "Our Community Management team will publish to Facebook, Instagram, and TikTok. Likewise, the Ads team will run campaigns with your designated budget.",

    "redes": "#social media",
    "see-services": "See Services",


    "footer.contact.title": "Contact Info",
    "footer.contact.phone": "Phone: +51 924 634 315",
    "footer.contact.email": "E-mail: ventas@postealab.com",
    "footer.contact.location": "Trujillo, Peru",

    "footer.explore.title": "Explore",
    "footer.explore.about": "About Us",
    "footer.explore.services": "Services",
    "footer.explore.portfolio": "Portfolio",
    "footer.explore.contact": "Contact",

    "footer.social.title": "Our Social Media",
    "footer.social.cta": "Get branding insights",
    "footer.social.subscribe": "Subscribe",

    "footer.bottom": "©2025 Postea Lab - All rights reserved"

  },
  es: {
    "nav.portafolio": "PORTAFOLIO",
    "nav.servicios": "SERVICIOS",
    "nav.branding": "BRANDING",
    "nav.redes": "REDES Y ANUNCIOS",
    "nav.web": "DISEÑO WEB",
    "nav.suscripcion": "SUSCRIPCIÓN",
    "nav.nosotros": "NOSOTROS",
    "nav.quienes": "QUIENES SOMOS",
    "nav.metodologia": "METODOLOGÍA",
    "nav.blog": "BLOG",
    "button.portafolio": "Portafolio",
    "hero.title.1": "Sé la marca",
    "hero.title.2": "elegida",
    "hero.title.3": "por tus clientes.",
    "hero.subtitle": "Somos una agencia de branding estratégico especializados en la creación y transformación de marcas, te ayudamos a crecer y diferenciarte.",
    "hero.stats.projects": "Proyectos Completados",
    "hero.stats.clients": "Clientes",
    "hero.stats.years": "Años de Experiencia",
    "hero.stats.countries": "Países",
    "portfolio.title": "Nuestro portafolio",
    "portfolio.description": "Desde tu nuevo logo hasta el manual visual y verbal, te equiparemos con las herramientas necesarias para (re)lanzarte con éxito como una marca alineada desde el primer día.",
    "portfolio.button": "Asesoría Gratuita",
    our_services: "Nuestros Servicios",
    branding: "Branding",
    social_media: "Social Media Estratégico",
    btl_activations: "Activaciones BTL",
    web_development: "Desarrollo Web",
    audiovisual_production: "Producción Audiovisual",
    advisory: "Asesoría y Análisis",
    see_more: "Ver más",
    "packages.title": "Nuestros Paquetes",
    "packages.description": "Nuestros paquetes son la base perfecta para cada marca, sin importar su tamaño.",
    "packages.tab.branding": "BRANDING",
    "packages.tab.social": "REDES SOCIALES + ADS",
    "packages.tab.web": "DESARROLLO WEB",
    "packages.branding.basic.title": "Branding Esencial",
    "packages.branding.basic.time": "2 - 3 SEMANAS",
    "packages.branding.basic.items.logo": "Diseño de logotipo (versión principal + versiones secundarias)",
    "packages.branding.basic.items.palette": "Paleta de colores y tipografías",
    "packages.branding.basic.items.manual": "Manual de marca (uso del logo, colores, estilo visual)",
    "packages.branding.basic.items.mockups": "Mockups para visualizar cómo lucirá tu marca en distintos soportes (tarjetas, papelería, redes)",
    "packages.branding.basic.items.social": "Diseños para redes sociales (perfil, portada y posts de presentación)",
    "packages.branding.basic.items.card": "Tarjeta de presentación digital",
    "packages.branding.basic.items.files": "Archivos editables listos para impresión y uso digital",
    "packages.branding.basic.price": "DESDE S/700 + IGV",
    "paquetes.redes.basico.titulo": "Paquete Básico",
    "paquetes.redes.basico.item1": "5 Reels Mensuales",
    "paquetes.redes.basico.item2": "5 Posts Mensuales",
    "paquetes.redes.basico.item3": "8 Historias (8 adaptaciones del contenido)",
    "paquetes.redes.basico.item4": "1 sesión de grabación",
    "paquetes.redes.basico.item5": "Fotografías mensuales",
    "paquetes.redes.basico.item6": "4 anuncios (ADS)",
    "paquetes.redes.basico.item7": "Asesoría Nivel 1",
    "paquetes.redes.basico.item8": "Contacto de influencers",
    "paquetes.redes.basico.item9": "Reunión estratégica incluida",
    "paquetes.redes.basico.precio": "S/1400",
    "paquetes.redes.premium.titulo": "Paquete Premium",
    "paquetes.redes.premium.item1": "6 Reels Mensuales",
    "paquetes.redes.premium.item2": "6 Posts Mensuales",
    "paquetes.redes.premium.item3": "Flyers impresos (4 tipos): papelería, letreros, etc.",
    "paquetes.redes.premium.item4": "12 Historias (12 adaptaciones del contenido)",
    "paquetes.redes.premium.item5": "2 sesiones de grabación",
    "paquetes.redes.premium.item6": "Fotografías mensuales",
    "paquetes.redes.premium.item7": "6 anuncios (ADS)",
    "paquetes.redes.premium.item8": "2 campañas mensuales",
    "paquetes.redes.premium.item9": "Informe de resultados (META)",
    "paquetes.redes.premium.item10": "Asesoría Nivel 2",
    "paquetes.redes.premium.item11": "Contacto con influencers",
    "paquetes.redes.premium.item12": "Reunión estratégica incluida",
    "paquetes.redes.premium.precio": "S/1800",
    "paquetes.redes.elite.titulo": "Paquete Elite",
    "paquetes.redes.elite.item1": "8 Reels Mensuales",
    "paquetes.redes.elite.item2": "10 Posts Mensuales",
    "paquetes.redes.elite.item3": "Flyers impresos (6 tipos): papelería, merchandising, letreros, etc.",
    "paquetes.redes.elite.item4": "18 Historias (18 adaptaciones del contenido)",
    "paquetes.redes.elite.item5": "2 sesiones de grabación",
    "paquetes.redes.elite.item6": "Fotografías mensuales",
    "paquetes.redes.elite.item7": "10 anuncios (ADS)",
    "paquetes.redes.elite.item8": "3 campañas mensuales",
    "paquetes.redes.elite.item9": "Informe de resultados (META + TikTok)",
    "paquetes.redes.elite.item10": "Asesoría Nivel 3",
    "paquetes.redes.elite.item11": "Contacto con influencers",
    "paquetes.redes.elite.item12": "Reunión estratégica incluida",
    "paquetes.redes.elite.precio": "S/2400",
    "paquetes.redes.tiempo": "X MES",

    "paquete.landing.title": "Elaboración de Landing Page",
    "paquete.landing.1": "Diseño único que refleje el estilo de tu marca",
    "paquete.landing.2": "Web rápida y compatible con celular, PC y tablet",
    "paquete.landing.3": "SEO para que Google te encuentre",
    "paquete.landing.4": "Enlaces directos a WhatsApp y redes sociales",
    "paquete.landing.5": "Galería de fotos y vídeos para tu marca",
    "paquete.landing.6": "Formulario para reservas y consultas",
    "paquete.landing.precio": "DESDE S/800 + IGV",

    "paquete.ecommerce.title": "E-commerce",
    "paquete.ecommerce.1": "Diseño responsive y personalizado",
    "paquete.ecommerce.2": "Integración con pasarelas de pago",
    "paquete.ecommerce.3": "Carrito de compras y checkout optimizado",
    "paquete.ecommerce.4": "Gestión total de productos y pedidos",
    "paquete.ecommerce.5": "Notificaciones automáticas",
    "paquete.ecommerce.6": "URLs amigables, carga rápida y uso adecuado de etiquetas",
    "paquete.ecommerce.precio": "DESDE S/... + IGV",

    "paquete.app.title": "Aplicaciones Web / Móvil / Escritorio",
    "paquete.app.1": "Apps web y móviles a medida",
    "paquete.app.2": "Login seguro y control de usuarios",
    "paquete.app.3": "Base de datos escalable y segura",
    "paquete.app.4": "Panel administrativo personalizado",
    "paquete.app.5": "Notificaciones push o en tiempo real",
    "paquete.app.6": "Integración con APIs y servicios externos",
    "paquete.app.precio": "DESDE S/... + IGV",

    "asesoria.boton": "Asesoría Gratuita",
    "clients.trust": "Ellos confían en nosotros",
    "question.title": "¿Tu negocio se siente así?",
    "question.description": "Si te identificas con esto, es momento de repensar tu estrategia de marca. En <strong>PosteaLab</strong>, te ayudamos a construir una identidad clara, coherente y poderosa.",
    "question.cta": "Asesoría gratuita",
    "question.list.item1": "Tu competencia tiene una propuesta clara, mientras tú sientes que estás en todas partes, sin un enfoque definido.",
    "question.list.item2": "Tu mensaje es inconsistente: cada persona del equipo describe el negocio de forma distinta.",
    "question.list.item3": "Te enfocas en vender productos, pero no en resolver los problemas reales de tus clientes.",
    "question.list.item4": "Estás por lanzar tu marca o producto y necesitas conectar con tu audiencia desde el primer día.",
    "question.list.item5": "Sientes que tu negocio necesita una dirección clara y un propósito bien definido.",
    "question.list.item6": "No estás satisfecho con la percepción actual de tu marca y sabes que puede llegar mucho más lejos.",
    
    "proceso.title": "Nuestro Proceso",
    "proceso.subtitle": "Dinámico y enfocado, no es solo nuestro equipo, es nuestro proceso.",
    "proceso.step1.title": "ON BOARDING",
    "proceso.step1.phase": "VISION",
    "proceso.step1.description": "Nos reunimos contigo y tu equipo para analizar las necesidades de crecimiento de tu negocio con el fin de asesorarte y brindarte nuestro análisis y recomendaciones.",
    "proceso.step2.title": "PROGRAMACIÓN",
    "proceso.step2.phase": "IDEALIZACIÓN",
    "proceso.step2.description": "Idealizamos el feed perfecto para ti y realizamos una lluvia de ideas con tu equipo para potenciar tu marca a través del contenido que crearemos.",
    "proceso.step3.title": "PRE-PRO-POST",
    "proceso.step3.phase": "PRODUCCIÓN",
    "proceso.step3.description": "Uno de nuestros líderes tomará tu proyecto y, junto con todo el equipo de Postea Lab, producirá todo el contenido del mes para darte un feed único, lleno de contenido de valor.",
    "proceso.step4.title": "DIFUSIÓN",
    "proceso.step4.phase": "PUBLICACIÓN Y MEDIOS",
    "proceso.step4.description": "Nuestro equipo de Community Management realizará las publicaciones en Facebook, Instagram y TikTok. Asimismo, el equipo de Ads llevará a cabo las campañas con el presupuesto que designes.",


    "redes": "#redes sociales",
    "see-services": "Ver Servicios",

    "footer.contact.title": "Info de contacto",
    "footer.contact.phone": "Celular: +51 924 634 315",
    "footer.contact.email": "E-mail: ventas@postealab.com",
    "footer.contact.location": "Trujillo, Perú",

    "footer.explore.title": "Explora",
    "footer.explore.about": "Nosotros",
    "footer.explore.services": "Servicios",
    "footer.explore.portfolio": "Portafolio",
    "footer.explore.contact": "Contacto",

    "footer.social.title": "Nuestras Redes",
    "footer.social.cta": "Recibe insights de branding",
    "footer.social.subscribe": "Suscríbete",

    "footer.bottom": "©2025 Postea Lab - Todos los derechos reservados"
  }
};


const langBtn = document.getElementById("lang-toggle");
let currentLang = "es";

langBtn.addEventListener("click", () => {
  currentLang = currentLang === "es" ? "en" : "es";
  translatePage(currentLang);
  langBtn.innerHTML = currentLang === "es"
    ? '<img src="./assets/language/en.svg" alt="English" /> EN'
    : '<img src="./assets/language/es.svg" alt="Español" /> ES';
});

function translatePage(lang) {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    const translation = translations[lang][key];

    if (translation) {
      el.innerHTML = translation; 
    } else {
      el.textContent = key;
    }
  });
}